name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  workflow_call:
    inputs:
      store_build_results:
        type: boolean
        default: false

jobs:
  build:
    name: Build
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: |
        CI=false
        npm run build

    - name: Pack build results
      if: ${{ inputs.store_build_results }}
      run: tar -czf build-${{ github.sha }}.tar.gz build

    - name: Upload workflow artifacts
      if: ${{ inputs.store_build_results }}
      uses: actions/upload-artifact@v3
      with:
        name: build-${{ github.sha }}
        path: build-${{ github.sha }}.tar.gz
        if-no-files-found: error
        retention-days: 1
