name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      store_build_results: true

  deploy:
    name: Deploy
    runs-on: [ubuntu-latest]
    environment: test
    needs: [build]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-${{ github.sha }}

      - name: Extract build results
        run: tar -xf build-${{ github.sha }}.tar.gz

      - name: Deploy app
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
