name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      store_build_results: true

  deploy:
    name: Deploy
    runs-on: [ubuntu-latest]
    environment: test
    needs: [build]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-${{ github.sha }}

      - name: Extract build results
        run: tar -xf build-${{ github.sha }}.tar.gz

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.REMOTE_HOST_SSH_KEY }}
          known_hosts: 'placeholder'

      - name: Adding known hosts
        run: ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on test stand
        env:
          HOST: ${{ secrets.REMOTE_HOST }}
          USER: ${{ secrets.REMOTE_HOST_USER }}
          TARGET_DIR: '/home/root/greatdo'
          OPTIONS: '-avz --progress --delete'
        run: rsync ${{ env.OPTIONS }} build/ ${{ env.USER }}@${{ env.HOST }}:${{ env.TARGET_DIR }}
